version: '3.1'

services:
  database:
    image: postgres:13-alpine
    container_name: nest_examples_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest_examples
    ports:
      - '5432:5432'
    volumes:
      - ./database-data:/var/lib/postgresql/data
