export enum EnvKey {
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  SERVER_PORT = 'SERVER_PORT',
  NODE_ENV = 'NODE_ENV',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  HASH_SALT_ROUNDS = 'HASH_SALT_ROUNDS',
}
